// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQxEhPXEumUhCn8yr0mC3kgmY3Rg-N-s',
    appId: '1:172696060119:web:11772a23c769e6b0dbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    authDomain: 'vinnote-4747a.firebaseapp.com',
    storageBucket: 'vinnote-4747a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfBCmaN27oMAzkAEl-Jdnjtl_iuyQJBE',
    appId: '1:172696060119:android:6ec6741bf5a5d4c0dbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    storageBucket: 'vinnote-4747a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQH6tZA7OgZfy1jNePBbzkJRAv2xOlJM',
    appId: '1:172696060119:ios:b00f7810489fa74bdbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    storageBucket: 'vinnote-4747a.appspot.com',
    androidClientId: '172696060119-58dvf03q164mksl2qbrlqsrkd0m10gk3.apps.googleusercontent.com',
    iosClientId: '172696060119-rb6cerhlt2ccnh2f00agtnmikv8t0a2d.apps.googleusercontent.com',
    iosBundleId: 'com.softy.vinno.vinnoFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmQH6tZA7OgZfy1jNePBbzkJRAv2xOlJM',
    appId: '1:172696060119:ios:88201535d2cfbed7dbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    storageBucket: 'vinnote-4747a.appspot.com',
    androidClientId: '172696060119-58dvf03q164mksl2qbrlqsrkd0m10gk3.apps.googleusercontent.com',
    iosClientId: '172696060119-7j4s71848f3kpretsa6h28j4f211quhv.apps.googleusercontent.com',
    iosBundleId: 'com.vinnofoods.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9fIQuVkCLus2RQkXaDvJDkePyxst7-zw',
    appId: '1:172696060119:web:e51a35265c387eacdbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    authDomain: 'vinnote-4747a.firebaseapp.com',
    storageBucket: 'vinnote-4747a.appspot.com',
  );
}
